### ISSUE TITLE
Building and Running Orix in Wine on Linux

### ISSUE THREAD

**Issue by seclorum** [oric-software/orix#46]
I have set up my Ubuntu system with Wine, and successfully installed the OSDK at C:\OSDK, with Orix intended to be at C:\ORIX, and so on... 

With a modified make.bat, I have been able to build Orix, however attempting to run it on  Oricutron gives me the results quoted below... Perhaps I am overlooking some tooling requirement, I am using the Oricutron currently bundled with the OSDK, with of course my own ROMs and so on.. Maybe this error below is more related to something Orix is expecting which the Linux build of Oricutron is lacking?

```
err:mmdevapi:DllGetClassObject Driver initialization failed
err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005
err:ole:CoGetClassObject no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
err:dsound:get_mmdevenum CoCreateInstance failed: 80004005

```

**Comment by jedeoric** [comment]
You need to have the last Oricutron version to have it working : 

You can compile Oricutron under linux.

**Comment by jedeoric** [comment]
You can also use Makefile under linux if you have xa compiled under linux, and xa is in your PATH.

When  you type "make", you will have all the rom orix folder (orixrom7, orixrom6,orixrom5 ...)

When oricutron had been compiled, you put in oricutron.cfg : 
telebank7=orixrom7
telebank6=orixrom6
telebank5=orixrom5 
...

Of course you must copy the rom in oricutron roms folder

Starts oricutron in telestrat mode

**Comment by jedeoric** [comment]
You can compile OSDK version under Linux : http://miniserve.defence-force.org/svn/public/pc/tools/osdk/main/

Did you manage to compile Oricutron ?

**Comment by seclorum** [comment]
I can compile (and have been using) Oricutron on my Linux machine for a long time now, so no worries there .. running Rev: 14f230d at the moment, but if this is outdated I can most certainly build it and run it.

I will have a look at getting xa built locally from the osdk sources, I guess I sorta just figured the distro 'xa' would suffice...

**Comment by seclorum** [comment]
Okay, so .. _int64 should be **int64_t** of course, and a few other things .. OSDK is building, but there don't seem to be rules for building the included XA in Linux, so I'm going to look at pinning to XA 2.2.5

**Comment by seclorum** [comment]
Really?  Interesting.  I'd be curious what our differences are .. because with _int64, the code is not portable..

**Comment by jedeoric** [comment]
you should use common make file : http://miniserve.defence-force.org/svn/public/pc/tools/osdk/main/
There is a Makefile which compile all OSDK source code. It should not work for pictconv, because it needs extra libs

**Comment by seclorum** [comment]
Okay, all caught up now -thanks for the pointer to the Makefile.  I now have Linux native toolchain, including even pictconv .. 'secret sauce' was knowing there was a good ol' Makefile, right there where you'd expect it ... ;)
